# Generated by Django 5.2.8 on 2025-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(default="Insight", max_length=50)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("short_description", models.TextField()),
                ("content", models.TextField()),
                ("cover_image", models.ImageField(upload_to="blogs/")),
                ("sub_title1", models.CharField(blank=True, max_length=200, null=True)),
                ("sub_content1", models.TextField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="blogs/"),
                ),
                ("sub_title2", models.CharField(blank=True, max_length=200, null=True)),
                ("sub_content2", models.TextField(blank=True, null=True)),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="blogs/"),
                ),
                ("sub_title3", models.CharField(blank=True, max_length=200, null=True)),
                ("sub_content3", models.TextField(blank=True, null=True)),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="blogs/"),
                ),
                ("sub_title4", models.CharField(blank=True, max_length=200, null=True)),
                ("sub_content4", models.TextField(blank=True, null=True)),
                ("published_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
